eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080
spring:
  application:
      name: budgets
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=budgetwise_budgets;trustServerCertificate=true
    username: andrey
    password: andrey100f
    jpa:
      hibernate:
        ddl-auto: none
application:
  config:
    expenses-url: http://localhost:8090/api/expenses