eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
    port: 8090
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=budgetwise_expenses;trustServerCertificate=true
    username: andrey
    password: andrey100f
    jpa:
      hibernate:
        ddl-auto: none
application:
  config:
    budgets-url: http://localhost:8080/api/budgets