eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowedMaxAge: 3600
      discovery:
        locator:
          enabled: true
      routes:
        - id: budgets
          uri: http://localhost:8080
          predicates:
            - Path=/api/budgets/**
        - id: expenses
          uri: http://localhost:8090
          predicates:
            - Path=/api/expenses/**
        - id: users
          uri: http://localhost:8060
          predicates:
              - Path=/api/users/**
        - id: auth
          uri: http://localhost:8050
          predicates:
              - Path=/api/auth/**