eureka:
  interface:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
    port: 8060
spring:
  application:
    name: users
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=budgetwise_users;trustServerCertificate=true
    username: andrey
    password: andrey100f
    jpa:
      hibernate:
        ddl-auto: none